site_name: PrintGO
repo_name: "2024.1-PrintGo-Doc"
repo_url: https://github.com/fga-eps-mds/2024.1-PrintGo-Doc
docs_dir: docs

theme:
  name: material
  language: pt
  features:
           - navigation.tabs
  logo: assets/logo/logoPrintGo.svg
  favicon: assets/logo/logoPrintGo.png

nav:
  - Home: 
    - Início: index.md
    - Guia de Contribuição: inicio/guia_contribuicao.md
  - Andamento:
    - Pré-sprints: 
      - Semana 1: andamento/semana1.md
      - Semana 2: andamento/semana2.md
      - Semana 3: andamento/semana3.md
      - Semana 5: andamento/semana5.md
  - Atas de Reunião:
    - Reuniões:
      - Reunião com POs dia 03/04/2024: atas/03-04.md
  - Documentos de Dojo:
    - Git: dojo/dojo-git.md

extra_css:
  - stylesheets/extra.css
