site_name: PrintGO
repo_name: "2024.1-PrintGo-Doc"
repo_url: https://github.com/fga-eps-mds/2024.1-PrintGo-Doc
docs_dir: docs

theme:
  name: material
  language: pt
  features:
           - navigation.tabs
  logo: assets/logo/logoPrintGo.svg
  favicon: assets/logo/logoPrintGo.png

nav:
  - Home:
    - Início: index.md
    - Guia de Contribuição: inicio/guia_contribuicao.md
  - Visão do Produto:
    - Lean Inception: visaoproduto/VisaoDoProduto.md
  - Documentos do Projeto:
    - Metodologias: documentos-projeto/metodologias.md
    - EAP: documentos-projeto/eap.md
    - Arquitetura: documentos-projeto/arquitetura.md
    - Identidade Visual: documentos-projeto/guia_de_estilo.md
  - Plano e Monitoramento:
    - Plano de Comunicação: plano-monitoramento/comunicacao.md
    - Plano de Custos: plano-monitoramento/plano-custos.md
    - Plano de Riscos: plano-monitoramento/plano-riscos.md
    - Plano de Qualidade: plano-monitoramento/plano-qualidade.md
  - Andamento:
    - Pré-sprints: 
      - Semana 1: andamento/semana1.md
      - Semana 2: andamento/semana2.md
      - Semana 3: andamento/semana3.md
      - semana 4: andamento/semana4.md
      - Semana 5: andamento/semana5.md
      - Semana 6: andamento/semana6.md
    # - Sprints:
    #   - Sprint 1:  {ADICIONA AQUI O DOCUMENTO DA SPRINT 1 E TIRA O COMENTARIO}
    
  # - Atas de Reunião:
  #   - Reuniões:
  #     - Reunião com POs dia 03/04/2024: atas/03-04.md
  #     - Reunião com POs dia 10/04/2024: atas/10-04.md
  #     - Reunião com POs dia 17/04/2024: atas/17-04.md
  #     - Reunião com POs dia 17/04/2024: atas/24-04.md
  # - Documentos de Dojo:
    # - Git: dojo/dojo-git.md



extra_css:
  - stylesheets/extra.css
