// Arquivo usado no https://dbdiagram.io

Table Padrao {
  id integer [primary key]
  nome varchar
  modelo varchar
  colorido bool
  oidModelo varchar
  oidNumeroSerie varchar
  oidFirmware varchar
  oidTempoAtivo varchar
  oidDigitalizacoes varchar
  oidCopiasPB varchar
  oidCopiasCor varchar
  oidTotalGeral varchar
  ativo bool
}

Table Impressora {
  id integer [primary key]
  numContrato varchar
  numSerie varchar
  enderecoIp varchar
  estaNaRede bool
  dataInstalacao datetime
  dataRetirada datetime
  ativo bool
  contadorInstalacaoPB integer
  contadorInstalacaoCor integer
  contadorAtualPB integer
  contadorAtualCor integer
  contadorRetiradaPB integer
  contadorRetiradaCor integer
  localizacao varchar
  padraoId integer
}

Table Relatorio {
  id                int         [pk, increment]
  impressoraId      int         [unique]
  contadorPB        int
  contadorPBDiff    int
  contadorCor       int
  contadorCorDiff   int
  ultimoResultado   int
  resultadoAtual    int
  ultimaAtualizacao datetime
}

Table RelatorioLocadora {
  id                int         [pk, increment]
  impressoraId      int         [unique]
  contadorPB        int
  contadorCor       int
  contadorTotal     int
}

Table RotinaSnmp {
  id                  int       [pk, increment]
  localizacao         varchar
  dataCriado          datetime  [default: `now()`]
  dataUltimoUpdate    datetime
  cronExpression      varchar
  ativo               bool
  cidadeTodas         bool
  regionalTodas       bool
  unidadeTodas        bool
}

Ref: Relatorio.impressoraId > Impressora.id
Ref: RelatorioLocadora.impressoraId > Impressora.id
Ref: Impressora.padraoId > Padrao.id
